# Generated by Django 4.2.15 on 2024-08-31 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teequeapp', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('D', 'Delievered'), ('R', 'Revision')], default='P', max_length=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teequeapp.order')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='teequeapp.service')),
            ],
        ),
    ]
