# Generated by Django 4.2.15 on 2024-09-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teequeapp', '0007_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
