# Generated by Django 4.2.15 on 2024-09-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teequeapp', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
