# Generated by Django 4.2.15 on 2024-09-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teequeapp', '0009_alter_customuser_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='service_id',
            new_name='service',
        ),
    ]
