# Generated by Django 4.2.15 on 2024-09-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teequeapp', '0012_rename_buyer_id_rating_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer_id',
            new_name='buyer',
        ),
    ]
