# Generated by Django 4.2.15 on 2024-09-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teequeapp', '0013_rename_buyer_id_order_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
